### ISSUE TITLE
Cannot read property 'toString' of null

### ISSUE THREAD

**Issue by i2801** [lubos/aws-lambda-wkhtmltopdf#6]
START RequestId: f4579180-138f-11e7-a480-b98cb89920aa Version: $LATEST
2017-03-28T08:24:26.695Z	f4579180-138f-11e7-a480-b98cb89920aa	TypeError: Cannot read property 'toString' of null
    at Response.<anonymous> (/var/task/index.js:27:45)
    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:360:18)
    at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/var/task/node_modules/aws-sdk/lib/request.js:673:14)
    at Request.transition (/var/task/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/task/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/task/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:675:12)
END RequestId: f4579180-138f-11e7-a480-b98cb89920aa
REPORT RequestId: f4579180-138f-11e7-a480-b98cb89920aa	Duration: 326.80 ms	Billed Duration: 400 ms 	Memory Size: 512 MB	Max Memory Used: 28 MB	
RequestId: f4579180-138f-11e7-a480-b98cb89920aa Process exited before completing request

**Comment by ryanray** [comment]
I have seen this issue twice. The first time the lambda wasn't able to execute `wkhtmltopdf` due to permissions... I fixed it with `chmod +x ./wkhtmltopdf` and then rezipping/uploading the file. The second time I saw it was when it couldn't decode the html.
